# allison_out_final.R

# Convert output files (burden estimates) provided by Allison with age-varying cfrs
# to vimc format
# Deaths and dalys will need to be computed using cases, cfrs and remaining life expectancy

# Convert output files (burden estimates) provided by Allison with time-varying cfrs to vimc format
create_central_burden_estimates <- function () {
  
  # scenario index to run
  for (index in 1:10) {  # debug #
    
    #  change these when new scenarios are released:
    scenario.name <- c("campaign-only-bestcase",           # 1  SIAs only
                       "mcv12-bestcase",                   # 2  MCV1&2
                       "campaign-bestcase",                # 3  MCV1&2 and SIAs
                       "mcv1-bestcase",                    # 4  MCV1 only
                       "campaign-only-default",            # 5  SIAs only
                       "mcv12-default",                    # 6  MCV1&2
                       "campaign-default",                 # 7  MCV1&2 and SIAs
                       "mcv1-default",                     # 8  MCV1 only
                       "no-vaccination",                   # 9  no vaccination (set vaccination and using_sia to 0)
                       "stop"                              # 10 MCV1&2 and SIAs
    )
    scenario <- scenario.name [index]
    
    # read central estimate file from original run
    burden <- fread (paste0 ("allison/allison_in/", "burden_estimate_Measles-LSHTM-Jit-", 
                             scenario, ".csv") )
    
    # add data column for remaining life expectancy
    lexp_remain       <- fread ("input/demographicdata2019/201910gavi-4_dds-201910_2_life_ex_both_full.csv") 
    
    burden <- lexp_remain [burden,
                           .(disease, year, age, i.country, country_name, cohort_size, cases, deaths, dalys, value),
                           on = .(country_code = country,
                                  age_from    <= age,
                                  age_to      >= age,
                                  year         = year)
                           ]
    
    setnames (burden, old = c("i.country", "value"), new = c("country", "remainLE"))
    
    # set disease column to Measles
    burden [, disease := NULL]
    burden [, disease := "Measles"]
    setcolorder (burden , neworder = c("disease"))
    
    # ----------------------------------------------------------------------------
    # read cfrs file generated by allison
    cfr_burden <- fread (paste0 ("allison/allison_out/cfr_", "Measles-LSHTM-Jit-", 
                                 scenario, ".csv") )
    
    # country cfrs are substituted for missing countries --  Palestine and Kosovo
    # Jordan for Palestine and Albania for Kosovo
    cfr_burden_PSE <- cfr_burden [country == "JOR"]
    cfr_burden_XK  <- cfr_burden [country == "ALB"]
    
    # change country names
    cfr_burden_PSE [, country := "PSE"]
    cfr_burden_XK  [, country := "XK"]
    
    # remove NA cfr rows for missing countries
    cfr_burden <- cfr_burden [!is.na (cfr)]
    
    # add cfr burden data tables for missing countries to the full cfr data table
    cfr_burden <- rbindlist (list (cfr_burden, 
                                   cfr_burden_PSE, 
                                   cfr_burden_XK), 
                             use.names = TRUE)
    
    # 2030 cfr copied to years 2031 - 2100 
    cfr_burden_rest <- rbindlist (lapply (X = 2031:2100, 
                                          FUN = function(i) copy(cfr_burden[year == 2030, ])[, year := i]))
    
    # combine cfr 2000-2030 plus 2031-2070
    cfr_burden <- rbindlist (list (cfr_burden, 
                                   cfr_burden_rest), 
                             use.names = TRUE)
    # ----------------------------------------------------------------------------
    
    # update central estimates from original run with age-varying cfrs
    # to get final central burden estimates
    final_burden <- cfr_burden [burden, 
                                .(i.disease, i.year, i.age, i.country, i.country_name, 
                                  i.cohort_size, i.cases, i.deaths, i.dalys, remainLE, cfr), 
                                on = .(year    = year, 
                                       age     = age, 
                                       country = country)
                                ]
    
    setnames (final_burden, 
              old = c ("i.disease", "i.year", "i.age", "i.country", "i.country_name", "i.cohort_size", "i.cases", "i.deaths", "i.dalys" ), 
              new = c (  "disease",   "year",   "age",   "country",   "country_name",   "cohort_size",   "cases",   "deaths",   "dalys" )
    )
    
    # calculate deaths
    final_burden [, deaths := cases * cfr]
    
    # calculate dalys = (ylds) + (ylls)
    final_burden [, dalys := ((cases - deaths) * 0.002) + (deaths * remainLE)]
    
    
    # drop extra columns for vimc format
    final_burden [, ':=' (remainLE = NULL, cfr = NULL)]
    
    # save central burden estimates
    fwrite (x = final_burden, 
            file = paste0 ("allison/final/", "central_burden_estimate_Measles-LSHTM-Jit-", 
                           scenario, ".csv") 
    )
  
  } # end of -- for (index in 1:10)
  
} # end of function -- create_central_burden_estimates 


# Convert output files (burden estimates) provided by Allison with time-varying cfrs to vimc format
create_central_burden_estimates ()


